import {
  ArrowRight,
  Check,
  CheckCircle,
  ChevronUp,
  Container,
  File,
  Folder,
  Globe,
  LayoutGrid,
  type LucideProps,
  Maximize,
  Menu,
  Minus,
  Play,
  Plus,
  RefreshCw,
  Search,
  Server,
  Square,
  Terminal,
  Trash2,
  X,
} from "lucide-react";

const SolidStop = (props: LucideProps) => <Square {...props} fill="currentColor" />;
const SolidPlay = (props: LucideProps) => <Play {...props} fill="currentColor" />;

export const Icons = {
  Plus,
  Minus,
  Trash: Trash2,
  Refresh: RefreshCw,
  CheckCircle,
  FitView: Maximize,
  Grid: LayoutGrid,
  X,
  Menu,
  Scan: Search,
  Check,
  Server,
  ArrowRight,
  Docker: Container,
  Terminal,
  Stop: SolidStop,
  Play: SolidPlay,
  Globe,
  Folder,
  File,
  ChevronUp,
};
